---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Import Dataset
```{r, echo=TRUE}
data <- read.csv("D:/WinSem_21-22/EDA/PROJECT/Employee_Attrition_Prediction_and_Analysis-main/HR_Employee_Data.csv")
```

# Summary of the Data
```{r, echo=TRUE}
head(data)
str(data)
library(dplyr) 
glimpse(data)
summary(data)
```


# Check for Null Values
```{r, echo=TRUE}
cbind(lapply(lapply(data, is.na), sum))
sum(is.na(data))
```

# Data Cleaning
```{r}
data$satisfaction_level<-gsub("%","",as.character(data$satisfaction_level))
data$satisfaction_level=as.integer(data$satisfaction_level)
head(data)
```


```{r, echo=TRUE}
data$last_evaluation<-gsub("%","",as.character(data$last_evaluation))
data$last_evaluation=as.integer(data$last_evaluation)
head(data)
```

```{r, error=TRUE}
library(tidyverse)
library(plotly)
library(ggplot2)
library(dplyr)
library(plotly)
library(hrbrthemes)
library(highcharter)
library(e1071)
library(caret)
library(kernlab)
library(caTools)
library(randomForest)

df <- data
head(df)
str(df)

data <- df%>%
  group_by(Department)%>%
  summarize(Avg_hrs = mean(average_montly_hours))

fig <- plot_ly(data, x = ~Department, y = ~Avg_hrs, type = 'bar', color = I("dark blue"))
fig <- fig %>% layout(title = "Average monthly working hours according to department",
         xaxis = list(title = "Department"),
         yaxis = list(title = "Average monthly working hours"))

fig

#ggplot(df,aes(x=number_project,y=average_montly_hours))+geom_jitter(aes(color=Department))

data <- df%>%
  filter(Work_accident==1)%>%
  group_by(Department)%>%
  summarize(No_of_wa = n())%>%
  arrange(No_of_wa)
head(data)

hc <- data %>% 
  hchart('line', hcaes(x = Department, y = No_of_wa))%>%
  hc_title(text = "Number of work accidents for each department")%>%
  hc_yAxis(title = "Number of work accidents")
hc

l <- df %>% filter(salary == "low")
m <- df %>% filter(salary == "medium")
h <- df %>% filter(salary == "high")

hc2 <- hchart(
  density(l$satisfaction_level), type = "area", 
  color = "steelblue", name = "Low Salary"
  ) %>%
  hc_add_series(
    density(m$satisfaction_level), type = "area",
    color = "#B71C1C", 
    name = "Medium Salary"
    )%>%
  hc_add_series(
    density(h$satisfaction_level), type = "area",
    color = "yellow", 
    name = "High Salary"
    )%>%
  hc_title(text = "Density plot of satisfaction level according to salary")%>%
  hc_xAxis(title = "Satisfaction Level (0-100)")
hc2

fig <- plot_ly(df, labels = ~Department, values = ~time_spend_company, type = 'pie')
fig <- fig %>% layout(title = 'Time spent per Department',
         xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
         yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))

fig
```

```{r, error=TRUE}
df2 <- df
df2$left <- as.factor(df2$left)
str(df2)

df2$ï..Emp_Id <- NULL

split <- sample.split(df2, SplitRatio = 0.7)
split

train <- subset(df2, split == "TRUE")
test <- subset(df2, split == "FALSE")

classifier = svm(formula = left ~ .,
                 data = train,
                 type = 'C-classification',
                 kernel = 'linear')

y_pred = predict(classifier, newdata = test[-7])
y_train_pred = predict(classifier, newdata = train[-7])

cm = table(test[, 7], y_pred)
cm
cm2 = table(train[, 7], y_train_pred )
cm2
```

```{r, error=TRUE}
# Splitting data in train and test data

# Fitting Random Forest to the train dataset
set.seed(120)  # Setting seed
classifier_RF = randomForest(x = train[-7],
                             y = train$left,
                             ntree = 50)

classifier_RF

# Predicting the Test set results
y_pred = predict(classifier_RF, newdata = test[-7])

# Confusion Matrix
confusion_mtx = table(test[, 7], y_pred)
confusion_mtx

# Plotting model
plot(classifier_RF)

# Importance plot
importance(classifier_RF)

# Variable importance plot
varImpPlot(classifier_RF)
```
